name: pyjanitor-dev
channels:
  - conda-forge
dependencies:
  - python>=3.6
  # required
  - pandas
  - pandas-flavor
  - multipledispatch
  - scipy

  # optional
  - biopython
  - natsort
  - pyspark>=3.2.0
  - rdkit
  - tqdm
  - unyt
  - xarray
  # io
  - openpyxl
  - xlrd

  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - hypothesis
  - pandas-vet
  - interrogate

  # dev tools
  - pip-tools
  - pre-commit
  - pylint
  - isort
  - make
  # release
  - twine

  # doc build
  - mkdocs
  - mkdocs-material
  - mkdocstrings<0.18.0
  - ipython
