name: pyjanitor-dev
channels:
  - conda-forge
dependencies:
  - python>=3.6
  # required
  - pandas
  - pandas-flavor
  - multipledispatch
  - scipy

  # optional
  - biopython
  - natsort
  - pyspark>=3.2.0
  - rdkit
  - tqdm
  - unyt
  - xarray
  - numba
  # io
  - openpyxl
  - xlrd

  # testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - hypothesis
  - pandas-vet
  - interrogate

  # dev
  - pip-tools
  - pre-commit
  - make
  # IDE code style
  - black
  - pylint
  - isort

  # doc
  - mkdocs
  - mkdocs-material
  - mkdocstrings-python
